#Give your project a name. Project names should contain only lowercase characters and underscores
#A good project name should reflect your organization's name or intended use
name: Fakestore
version: '1.0.0'
config-version: 2

#This setting configures the profile that dbt will use for this project
profile: 'Fakestore'

#This configurations specify where dbt should look for different types of files. 
#The source-paths configuration, for example, states that models in this project can be found in the
# "models/" directory.
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["test"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshot"]
#docs-path: []
#asset-paths: []
#log-path: "log"
#packages-installed-path: 
target-path: "target" #directory which will store compiled SQL files
#clean-target: #directories to be removed by 'dbt clean'
  #- "target"
  #- "dbt_packages"

#Configure how models should be mterialized
#This configuration can be overridden in the individual model files using the '{{config(..)}}' macro
#Full documentation: https://docs.getdbt.com/configuring-models
models:
  Fakestore:
    staging:
      materialized: view
    marts:
      materialized: view



